-- AUTO-GENERATED by scripts/generate-courts-seed.mjs from data/courts.json. Do not edit.
begin;
select plan(8);
select is((select count(*) from public.courts where is_active), 82::bigint,
  'active courts match data/courts.json (82 entries)');
select is((select count(*) from public.courts where is_active and (city is null or city not in ('台北市', '新北市'))), 0::bigint,
  'every active court has a valid city from data/courts.json');
select is((select count(*) from public.courts where is_active and city = '新北市'), 29::bigint,
  'New Taipei courts remain in the raw active catalogue');
select is((select count(*) from public.courts where is_active and name in
  ('台北網球中心','百齡河濱公園網球場','青年公園網球場')),
  3::bigint, 'legacy real-three join-key courts remain active');
select is((select count(*) from public.courts where name in ('大安森林公園網球場','中正網球中心','迎風河濱公園網球場') and is_active), 0::bigint, 'fictional legacy courts are deactivated');
select is((select count(*) from public.courts where name in ('大安森林公園網球場','中正網球中心','迎風河濱公園網球場') and city is null), 3::bigint,
  'fictional legacy courts retain a null city');
set local role anon;
select is((select count(*) from public.courts), 82::bigint, 'anon reads exactly the active catalog');
select is((select count(*) from public.courts where name = '三和國中網球場'), 1::bigint,
  'sample court is anon-readable');
select * from finish();
rollback;
