-- AUTO-GENERATED by scripts/generate-courts-seed.mjs from data/courts.json. Do not edit.
begin;
select plan(4);
select is((select count(*) from public.courts where is_active), 6::bigint,
  'active courts match data/courts.json (6 entries)');
select is((select count(*) from public.courts where is_active and name in
  ('台北網球中心','大安森林公園網球場','中正網球中心','迎風河濱公園網球場','百齡河濱公園網球場','青年公園網球場')),
  6::bigint, 'legacy six join-key courts remain active');
set local role anon;
select is((select count(*) from public.courts), 6::bigint, 'anon reads exactly the active catalog');
select is((select count(*) from public.courts where name = '台北網球中心'), 1::bigint,
  'sample court is anon-readable');
select * from finish();
rollback;
