import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

const flushSyncImportRestriction = {
  name: "react-dom",
  importNames: ["flushSync"],
  message: "禁止直接匯入 flushSync；請改由 syncCommit.ts 的單一同步 commit 邊界呼叫。",
};

const reactDomSyntaxRestrictions = [
  {
    selector: 'ImportDeclaration[source.value="react-dom"] ImportNamespaceSpecifier',
    message: "禁止 namespace 匯入 react-dom；請使用核可的具名匯入，並由 syncCommit.ts 呼叫同步 commit。",
  },
  {
    selector: 'ImportDeclaration[source.value="react-dom"] ImportDefaultSpecifier',
    message: "禁止 default 匯入 react-dom；請使用核可的具名匯入，並由 syncCommit.ts 呼叫同步 commit。",
  },
  {
    selector: 'ImportExpression[source.value="react-dom"]',
    message: "禁止動態匯入 react-dom；請使用核可的靜態具名匯入，並由 syncCommit.ts 呼叫同步 commit。",
  },
];

export default tseslint.config(
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  {
    files: ["src/**/*.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: globals.browser,
    },
  },
  {
    files: ["tests/**/*.{js,mjs}"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: [
      "tests/**/*.spec.js",
      "tests/sheets-dom.test.js",
      "tests/fixtures/appRuntime.js",
      "tests/fixtures/fakeMaps.js",
      "tests/fixtures/localSupabase.js",
      "tests/fixtures/smoke.js",
    ],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    files: ["scripts/**/*.{js,mjs}", "eslint.config.js", "prettier.config.js", "playwright.config.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: ["src/**/*.{ts,tsx}", "vite.config.ts"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    plugins: {
      "react-hooks": reactHooks,
    },
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      // 既有 type-aware 型別債，本批不改變既有程式語意。
      "@typescript-eslint/unbound-method": "off",
      "react-hooks/exhaustive-deps": "error",
      "react-hooks/rules-of-hooks": "error",
    },
  },
  // `src/data/databaseTypes.ts:1` is generated by `npm run db:gen-types`;
  // type-aware ESLint restoration plan §5 option 1 keeps its two generated findings as tracked debt.
  {
    files: ["src/data/databaseTypes.ts"],
    rules: {
      "@typescript-eslint/no-redundant-type-constituents": "off",
    },
  },
  // Phase E unbound-method 逐批恢復：已清零的檔案以 scoped override 先上線，
  // 全庫清零後移除本區塊與全域 off。
  {
    files: ["src/map.ts"],
    rules: {
      "@typescript-eslint/unbound-method": "error",
    },
  },
  // Keep these ranges disjoint: flat-config rule arrays replace rather than merge.
  // Non-data source retains both the data boundary and the synchronous-commit boundary.
  {
    files: ["src/**/*.{js,ts,tsx}"],
    ignores: ["src/data/**", "src/dataApi.ts", "src/syncCommit.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [flushSyncImportRestriction],
          patterns: [
            {
              group: ["**/supabaseClient", "**/supabaseClient.*"],
              message: "禁止直接匯入 supabaseClient；請改由 dataApi facade 存取。",
            },
            {
              group: ["**/data/mappers/**"],
              message: "禁止直接匯入 data 內部 mapper；請改由 dataApi facade 存取。",
            },
            {
              regex: "(?:^|/)data/mappers/?$",
              message: "禁止直接匯入 data 內部 mapper；請改由 dataApi facade 存取。",
            },
            {
              group: ["**/data/repositories/**"],
              message: "禁止直接匯入 data 內部 repository；請改由 dataApi facade 存取。",
            },
            {
              regex: "(?:^|/)data/repositories/?$",
              message: "禁止直接匯入 data 內部 repository；請改由 dataApi facade 存取。",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        ...reactDomSyntaxRestrictions,
        {
          selector:
            "ImportExpression[source.value=/(?:^|\\/)supabaseClient(?:\\.|$)|(?:^|\\/)data\\/(?:mappers|repositories)(?:\\/|$)/]",
          message: "禁止動態匯入資料層內部；請改由 dataApi facade 存取。",
        },
        {
          selector: 'ImportExpression:not([source.type="Literal"])',
          message: "動態 import 路徑必須使用字串 literal，以便靜態驗證資料邊界。",
        },
      ],
    },
  },
  // Data internals are exempt only from the facade rule, not from the synchronous-commit boundary.
  {
    files: ["src/data/**/*.{js,ts,tsx}", "src/dataApi.ts"],
    rules: {
      "no-restricted-imports": ["error", { paths: [flushSyncImportRestriction] }],
      "no-restricted-syntax": ["error", ...reactDomSyntaxRestrictions],
    },
  }
);
