// Generated by scripts/generate-court-guide-catalog.mjs; edit data/court-guides.json.
// Only published Taipei guides enter browser intents; nationwide drafts never enter this map.
export const COURT_GUIDE_NAMES = {
  "youth-park": "青年公園網球場",
  "rainbow-riverside": "彩虹河濱公園網球場",
  "taipei-tennis-center": "台北網球中心",
  "dajia-riverside": "大佳河濱公園網球場",
  "meiti-riverside": "美堤河濱公園網球場",
  "huazhong-riverside": "華中河濱公園網球場",
  "zhongzheng-riverside": "中正河濱公園網球場",
  "guting-riverside": "古亭河濱公園網球場",
  "daonan-riverside": "道南河濱公園網球場",
  "yanping-riverside": "延平河濱公園網球場",
  "bailing-riverside": "百齡河濱公園網球場",
  "guanshan-riverside": "觀山河濱公園網球場",
  "chengmei-right-bank": "成美右岸河濱公園網球場",
  "minquan-park": "民權公園網球場",
  "taipei-tennis-court": "台北網球場",
} as const;
