// Local-only demo data. It intentionally uses the same public SessionSummary
// shape as the configured API and never represents a real person or external
// post. The real courts below are verified entries from data/courts.json.

export const COURTS = [
  { id: 101, name: "台北網球中心", city: "台北市", district: "內湖區", lat: 25.067446, lng: 121.596648 },
  { id: 102, name: "大佳河濱公園網球場", city: "台北市", district: "中山區", lat: 25.074849, lng: 121.531508 },
  { id: 103, name: "古亭河濱公園網球場", city: "台北市", district: "中正區", lat: 25.019024, lng: 121.522689 },
  { id: 104, name: "彩虹河濱公園網球場", city: "台北市", district: "內湖區", lat: 25.062687, lng: 121.571815 },
  { id: 105, name: "百齡河濱公園網球場", city: "台北市", district: "士林區", lat: 25.08896, lng: 121.512494 },
  { id: 106, name: "青年公園網球場", city: "台北市", district: "萬華區", lat: 25.02306, lng: 121.506928 },
];

// Local-only player-directory examples. They are fictional and deliberately
// contain only the public fields returned by player_directory.
export const MOCK_PLAYERS = [
  {
    profileId: 8001,
    nickname: "示範山嵐",
    ntrp: 3.5,
    playTypes: ["單打", "對拉"],
    slotCodes: ["we-m", "we-a"],
    courtId: 101,
    courtName: "台北網球中心",
    courtDistrict: "內湖區",
    courtLat: 25.067446,
    courtLng: 121.596648,
    isSelf: false,
  },
  {
    profileId: 8002,
    nickname: "示範海風",
    ntrp: 4.0,
    playTypes: ["雙打"],
    slotCodes: ["wd-e"],
    courtId: 101,
    courtName: "台北網球中心",
    courtDistrict: "內湖區",
    courtLat: 25.067446,
    courtLng: 121.596648,
    isSelf: false,
  },
  {
    profileId: 8003,
    nickname: "示範杉林",
    ntrp: 2.5,
    playTypes: ["練球"],
    slotCodes: ["we-e"],
    courtId: 102,
    courtName: "大佳河濱公園網球場",
    courtDistrict: "中山區",
    courtLat: 25.074849,
    courtLng: 121.531508,
    isSelf: false,
  },
];

const futureStartAt = (daysFromNow, hourOffset = 0) =>
  new Date(Date.now() + (daysFromNow * 24 + hourOffset) * 60 * 60 * 1000).toISOString();
const ongoingStartAt = (minutesAgo) => new Date(Date.now() - minutesAgo * 60 * 1000).toISOString();

// Do not add contact data, profile identifiers, source links, or imported
// social-post wording here. These payloads are deliberately render-safe.
export const MOCK_SESSIONS = [
  {
    sessionId: 9001,
    sportCode: "tennis",
    courtId: 101,
    court: "台北網球中心",
    courtDistrict: "內湖區",
    courtLat: 25.067446,
    courtLng: 121.596648,
    startAt: ongoingStartAt(60),
    playType: "對拉",
    ntrpMin: 3,
    ntrpMax: 4,
    slotsTotal: 2,
    slotsRemaining: 1,
    notes: "本機示範資料：一起進行固定節奏的對拉練習。",
    hostNickname: "示範松果",
    hostNtrp: 3.5,
    hostProfileComplete: true,
    status: "open",
    joinMode: "approval",
  },
  {
    sessionId: 9002,
    sportCode: "tennis",
    courtId: 102,
    court: "大佳河濱公園網球場",
    courtDistrict: "中山區",
    courtLat: 25.074849,
    courtLng: 121.531508,
    startAt: futureStartAt(2, 1),
    playType: "雙打",
    ntrpMin: 3,
    ntrpMax: 4.5,
    slotsTotal: 3,
    slotsRemaining: 2,
    notes: "本機示範資料：友善雙打輪轉，請以球局流程申請加入。",
    hostNickname: "示範雲朵",
    hostNtrp: 3.5,
    hostProfileComplete: true,
    status: "open",
    joinMode: "instant",
  },
  {
    sessionId: 9003,
    sportCode: "tennis",
    courtId: 103,
    court: "古亭河濱公園網球場",
    courtDistrict: "中正區",
    courtLat: 25.019024,
    courtLng: 121.522689,
    startAt: futureStartAt(3, 3),
    playType: "單打",
    ntrpMin: 4,
    ntrpMax: 5,
    slotsTotal: 1,
    slotsRemaining: 0,
    notes: "本機示範資料：目前額滿，保留作為球局狀態展示。",
    hostNickname: "示範彗星",
    hostNtrp: 4.5,
    hostProfileComplete: true,
    status: "full",
    joinMode: "approval",
  },
  {
    sessionId: 9004,
    sportCode: "tennis",
    courtId: 104,
    court: "彩虹河濱公園網球場",
    courtDistrict: "內湖區",
    courtLat: 25.062687,
    courtLng: 121.571815,
    startAt: futureStartAt(4, 2),
    playType: "練球",
    ntrpMin: null,
    ntrpMax: null,
    slotsTotal: 2,
    slotsRemaining: 2,
    notes: "本機示範資料：基礎擊球與步伐練習，不限程度區間。",
    hostNickname: "示範月光",
    hostNtrp: 2.5,
    hostProfileComplete: true,
    status: "open",
    joinMode: "approval",
  },
  {
    sessionId: 9005,
    sportCode: "tennis",
    courtId: 105,
    court: "百齡河濱公園網球場",
    courtDistrict: "士林區",
    courtLat: 25.08896,
    courtLng: 121.512494,
    startAt: futureStartAt(5, 1),
    playType: "單打",
    ntrpMin: 3.5,
    ntrpMax: 4.5,
    slotsTotal: 1,
    slotsRemaining: 1,
    notes: "本機示範資料：單打友誼賽，以安全的球局卡內容呈現。",
    hostNickname: "示範海星",
    hostNtrp: 4,
    hostProfileComplete: true,
    status: "open",
    joinMode: "approval",
  },
  {
    sessionId: 9006,
    sportCode: "tennis",
    courtId: 106,
    court: "青年公園網球場",
    courtDistrict: "萬華區",
    courtLat: 25.02306,
    courtLng: 121.506928,
    startAt: futureStartAt(6, 2),
    playType: "雙打",
    ntrpMin: 2.5,
    ntrpMax: 3.5,
    slotsTotal: 3,
    slotsRemaining: 1,
    notes: "本機示範資料：輕鬆雙打練習，資料不會送往任何外部服務。",
    hostNickname: "示範琥珀",
    hostNtrp: 3,
    hostProfileComplete: true,
    status: "open",
    joinMode: "approval",
  },
];
