create or replace view public.session_discovery with (security_barrier=true, security_invoker=false) as
select session_row.id, session_row.id as session_id, sport_row.code as sport_code, session_row.court_id, court_row.name as court, court_row.district as court_district, court_row.lat as court_lat, court_row.lng as court_lng, session_row.start_at, session_row.play_type, session_row.ntrp_min, session_row.ntrp_max, session_row.slots_total,
  (session_row.slots_total-count(participant_row.id) filter(where participant_row.role='guest' and participant_row.status='accepted'))::smallint as slots_remaining,
  session_row.notes, host_profile.nickname as host_nickname, host_profile.ntrp as host_ntrp, private.profile_meets_gate(host_profile.id,'ntrp') as host_profile_complete, session_row.status, session_row.join_mode, session_row.venue_type, session_row.range_end,
  case when session_row.venue_type='candidates' then (select array_agg(candidate_court.court_id order by candidate_court.position) from public.session_candidate_courts candidate_court where candidate_court.session_id=session_row.id) else null end as candidate_court_ids,
  session_row.fee_note, session_row.decided_at
from public.sessions session_row join public.sports sport_row on sport_row.id=session_row.sport_id join public.courts court_row on court_row.id=session_row.court_id join public.profiles host_profile on host_profile.id=session_row.host_profile_id left join public.session_participants participant_row on participant_row.session_id=session_row.id
where session_row.status in ('open','full') and (case when session_row.venue_type='candidates' and session_row.decided_at is null then session_row.start_at>now() else session_row.start_at+interval '2 hours'>now() end) and sport_row.code='tennis' and sport_row.is_active and court_row.is_active and court_row.city='台北市'
group by session_row.id,sport_row.code,court_row.name,court_row.district,court_row.lat,court_row.lng,host_profile.id,host_profile.nickname,host_profile.ntrp,session_row.join_mode;
