-- AUTO-GENERATED by scripts/generate-courts-seed.mjs from data/courts.json (6 座)。請勿手改;改 data/courts.json 後重生。
insert into public.courts (name, district, lat, lng)
values
  ('台北網球中心', '內湖區', 25.069000, 121.593000),
  ('彩虹河濱公園網球場', '內湖區', 25.062687, 121.571815),
  ('華中河濱公園網球場', '萬華區', 25.017174, 121.491658),
  ('古亭河濱公園網球場', '中正區', 25.019024, 121.522689),
  ('百齡河濱公園網球場', '士林區', 25.089000, 121.514000),
  ('青年公園網球場', '萬華區', 25.022000, 121.504000)
on conflict (name) do update
set district = excluded.district, lat = excluded.lat, lng = excluded.lng,
    is_active = true, updated_at = now();

-- 目錄外球場一律停用(不 DELETE:profile_courts/partner_requests 為 on delete restrict)
update public.courts
set is_active = false, updated_at = now()
where name not in ('台北網球中心', '彩虹河濱公園網球場', '華中河濱公園網球場', '古亭河濱公園網球場', '百齡河濱公園網球場', '青年公園網球場');
