// Generated by `npm run db:gen-types`. Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      court_subscriptions: {
        Row: {
          court_id: number;
          created_at: string;
          profile_id: number;
        };
        Insert: {
          court_id: number;
          created_at?: string;
          profile_id: number;
        };
        Update: {
          court_id?: number;
          created_at?: string;
          profile_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "court_subscriptions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "court_subscriptions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "court_subscriptions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "court_subscriptions_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "court_subscriptions_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "court_subscriptions_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      courts: {
        Row: {
          city: string | null;
          created_at: string;
          district: string;
          id: number;
          is_active: boolean;
          lat: number;
          lng: number;
          name: string;
          updated_at: string;
        };
        Insert: {
          city?: string | null;
          created_at?: string;
          district: string;
          id?: never;
          is_active?: boolean;
          lat: number;
          lng: number;
          name: string;
          updated_at?: string;
        };
        Update: {
          city?: string | null;
          created_at?: string;
          district?: string;
          id?: never;
          is_active?: boolean;
          lat?: number;
          lng?: number;
          name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_outbox: {
        Row: {
          attempts: number;
          created_at: string;
          event_type: string;
          id: number;
          payload: Json;
          recipient_profile_id: number;
          sent_at: string | null;
          session_id: number;
        };
        Insert: {
          attempts?: number;
          created_at?: string;
          event_type: string;
          id?: never;
          payload: Json;
          recipient_profile_id: number;
          sent_at?: string | null;
          session_id: number;
        };
        Update: {
          attempts?: number;
          created_at?: string;
          event_type?: string;
          id?: never;
          payload?: Json;
          recipient_profile_id?: number;
          sent_at?: string | null;
          session_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "notification_outbox_recipient_profile_id_fkey";
            columns: ["recipient_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "notification_outbox_recipient_profile_id_fkey";
            columns: ["recipient_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "notification_outbox_recipient_profile_id_fkey";
            columns: ["recipient_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_outbox_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_outbox_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "notification_outbox_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_outbox_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "notification_outbox_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "notification_outbox_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      notification_prefs: {
        Row: {
          chat_message_enabled: boolean;
          guest_invited_enabled: boolean;
          guest_request_reviewed_enabled: boolean;
          host_new_request_enabled: boolean;
          profile_id: number;
          session_reminder_enabled: boolean;
          session_updated_enabled: boolean;
        };
        Insert: {
          chat_message_enabled?: boolean;
          guest_invited_enabled?: boolean;
          guest_request_reviewed_enabled?: boolean;
          host_new_request_enabled?: boolean;
          profile_id: number;
          session_reminder_enabled?: boolean;
          session_updated_enabled?: boolean;
        };
        Update: {
          chat_message_enabled?: boolean;
          guest_invited_enabled?: boolean;
          guest_request_reviewed_enabled?: boolean;
          host_new_request_enabled?: boolean;
          profile_id?: number;
          session_reminder_enabled?: boolean;
          session_updated_enabled?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "notification_prefs_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "notification_prefs_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "notification_prefs_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      player_blocks: {
        Row: {
          blocked_profile_id: number;
          blocker_profile_id: number;
          created_at: string;
        };
        Insert: {
          blocked_profile_id: number;
          blocker_profile_id: number;
          created_at?: string;
        };
        Update: {
          blocked_profile_id?: number;
          blocker_profile_id?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "player_blocks_blocked_profile_id_fkey";
            columns: ["blocked_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_blocks_blocked_profile_id_fkey";
            columns: ["blocked_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_blocks_blocked_profile_id_fkey";
            columns: ["blocked_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "player_blocks_blocker_profile_id_fkey";
            columns: ["blocker_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_blocks_blocker_profile_id_fkey";
            columns: ["blocker_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_blocks_blocker_profile_id_fkey";
            columns: ["blocker_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      player_presence: {
        Row: {
          court_id: number;
          profile_id: number;
          updated_at: string;
        };
        Insert: {
          court_id: number;
          profile_id: number;
          updated_at?: string;
        };
        Update: {
          court_id?: number;
          profile_id?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "player_presence_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "player_presence_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "player_presence_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "player_presence_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_presence_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_presence_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profile_courts: {
        Row: {
          court_id: number;
          created_at: string;
          profile_id: number;
        };
        Insert: {
          court_id: number;
          created_at?: string;
          profile_id: number;
        };
        Update: {
          court_id?: number;
          created_at?: string;
          profile_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "profile_courts_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profile_courts_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "profile_courts_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "profile_courts_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "profile_courts_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "profile_courts_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profile_play_types: {
        Row: {
          created_at: string;
          play_type: string;
          profile_id: number;
        };
        Insert: {
          created_at?: string;
          play_type: string;
          profile_id: number;
        };
        Update: {
          created_at?: string;
          play_type?: string;
          profile_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "profile_play_types_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "profile_play_types_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "profile_play_types_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profile_slots: {
        Row: {
          created_at: string;
          profile_id: number;
          slot_code: string;
        };
        Insert: {
          created_at?: string;
          profile_id: number;
          slot_code: string;
        };
        Update: {
          created_at?: string;
          profile_id?: number;
          slot_code?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profile_slots_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "profile_slots_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "profile_slots_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          id: number;
          is_public: boolean;
          line_id: string | null;
          nickname: string | null;
          ntrp: number | null;
          open_to_greeting: boolean;
          share_presence: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          id?: never;
          is_public?: boolean;
          line_id?: string | null;
          nickname?: string | null;
          ntrp?: number | null;
          open_to_greeting?: boolean;
          share_presence?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          id?: never;
          is_public?: boolean;
          line_id?: string | null;
          nickname?: string | null;
          ntrp?: number | null;
          open_to_greeting?: boolean;
          share_presence?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          auth: string;
          created_at: string;
          endpoint: string;
          id: number;
          p256dh: string;
          profile_id: number;
        };
        Insert: {
          auth: string;
          created_at?: string;
          endpoint: string;
          id?: never;
          p256dh: string;
          profile_id: number;
        };
        Update: {
          auth?: string;
          created_at?: string;
          endpoint?: string;
          id?: never;
          p256dh?: string;
          profile_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "push_subscriptions_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "push_subscriptions_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      reports: {
        Row: {
          created_at: string;
          id: number;
          message_id: number | null;
          reason: string;
          reported_profile_id: number | null;
          reporter_profile_id: number;
          session_id: number | null;
          status: string;
        };
        Insert: {
          created_at?: string;
          id?: never;
          message_id?: number | null;
          reason: string;
          reported_profile_id?: number | null;
          reporter_profile_id: number;
          session_id?: number | null;
          status?: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          message_id?: number | null;
          reason?: string;
          reported_profile_id?: number | null;
          reporter_profile_id?: number;
          session_id?: number | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reports_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "session_message_feed";
            referencedColumns: ["message_id"];
          },
          {
            foreignKeyName: "reports_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "session_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_reported_profile_id_fkey";
            columns: ["reported_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "reports_reported_profile_id_fkey";
            columns: ["reported_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "reports_reported_profile_id_fkey";
            columns: ["reported_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_reporter_profile_id_fkey";
            columns: ["reporter_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "reports_reporter_profile_id_fkey";
            columns: ["reporter_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "reports_reporter_profile_id_fkey";
            columns: ["reporter_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "reports_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "reports_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "reports_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      session_candidate_courts: {
        Row: {
          court_id: number;
          position: number;
          session_id: number;
        };
        Insert: {
          court_id: number;
          position: number;
          session_id: number;
        };
        Update: {
          court_id?: number;
          position?: number;
          session_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "session_candidate_courts_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_candidate_courts_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "session_candidate_courts_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "session_candidate_courts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_candidate_courts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_candidate_courts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_candidate_courts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_candidate_courts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_candidate_courts_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      session_chat_read_cursors: {
        Row: {
          last_read_message_id: number;
          profile_id: number;
          session_id: number;
          updated_at: string;
        };
        Insert: {
          last_read_message_id?: number;
          profile_id: number;
          session_id: number;
          updated_at?: string;
        };
        Update: {
          last_read_message_id?: number;
          profile_id?: number;
          session_id?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "session_chat_read_cursors_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_chat_read_cursors_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      session_messages: {
        Row: {
          body: string;
          created_at: string;
          id: number;
          kind: string;
          sender_profile_id: number | null;
          session_id: number;
        };
        Insert: {
          body: string;
          created_at?: string;
          id?: never;
          kind?: string;
          sender_profile_id?: number | null;
          session_id: number;
        };
        Update: {
          body?: string;
          created_at?: string;
          id?: never;
          kind?: string;
          sender_profile_id?: number | null;
          session_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "session_messages_sender_profile_id_fkey";
            columns: ["sender_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_messages_sender_profile_id_fkey";
            columns: ["sender_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_messages_sender_profile_id_fkey";
            columns: ["sender_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      session_participants: {
        Row: {
          created_at: string;
          id: number;
          initiated_by: string;
          played_confirmed: boolean;
          profile_id: number;
          role: string;
          session_id: number;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: never;
          initiated_by?: string;
          played_confirmed?: boolean;
          profile_id: number;
          role: string;
          session_id: number;
          status: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          initiated_by?: string;
          played_confirmed?: boolean;
          profile_id?: number;
          role?: string;
          session_id?: number;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      sessions: {
        Row: {
          archived_at: string | null;
          court_id: number;
          created_at: string;
          decided_at: string | null;
          fee_note: string | null;
          host_profile_id: number;
          id: number;
          join_mode: string;
          notes: string | null;
          ntrp_max: number | null;
          ntrp_min: number | null;
          play_type: string;
          range_end: string | null;
          slots_total: number;
          sport_id: number;
          start_at: string;
          status: string;
          updated_at: string;
          venue_type: string;
        };
        Insert: {
          archived_at?: string | null;
          court_id: number;
          created_at?: string;
          decided_at?: string | null;
          fee_note?: string | null;
          host_profile_id: number;
          id?: never;
          join_mode?: string;
          notes?: string | null;
          ntrp_max?: number | null;
          ntrp_min?: number | null;
          play_type: string;
          range_end?: string | null;
          slots_total: number;
          sport_id: number;
          start_at: string;
          status?: string;
          updated_at?: string;
          venue_type?: string;
        };
        Update: {
          archived_at?: string | null;
          court_id?: number;
          created_at?: string;
          decided_at?: string | null;
          fee_note?: string | null;
          host_profile_id?: number;
          id?: never;
          join_mode?: string;
          notes?: string | null;
          ntrp_max?: number | null;
          ntrp_min?: number | null;
          play_type?: string;
          range_end?: string | null;
          slots_total?: number;
          sport_id?: number;
          start_at?: string;
          status?: string;
          updated_at?: string;
          venue_type?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "sessions_host_profile_id_fkey";
            columns: ["host_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "sessions_host_profile_id_fkey";
            columns: ["host_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "sessions_host_profile_id_fkey";
            columns: ["host_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_sport_id_fkey";
            columns: ["sport_id"];
            isOneToOne: false;
            referencedRelation: "sports";
            referencedColumns: ["id"];
          },
        ];
      };
      sports: {
        Row: {
          code: string;
          created_at: string;
          id: number;
          is_active: boolean;
          name: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          id?: never;
          is_active?: boolean;
          name: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          id?: never;
          is_active?: boolean;
          name?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      my_player_blocks: {
        Row: {
          blocked_nickname: string | null;
          blocked_profile_id: number | null;
          created_at: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "player_blocks_blocked_profile_id_fkey";
            columns: ["blocked_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_blocks_blocked_profile_id_fkey";
            columns: ["blocked_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "player_blocks_blocked_profile_id_fkey";
            columns: ["blocked_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      my_profile: {
        Row: {
          court_ids: number[] | null;
          is_public: boolean | null;
          line_id: string | null;
          nickname: string | null;
          ntrp: number | null;
          open_to_greeting: boolean | null;
          play_types: string[] | null;
          share_presence: boolean | null;
          slot_codes: string[] | null;
        };
        Insert: {
          court_ids?: never;
          is_public?: boolean | null;
          line_id?: string | null;
          nickname?: string | null;
          ntrp?: number | null;
          open_to_greeting?: boolean | null;
          play_types?: never;
          share_presence?: boolean | null;
          slot_codes?: never;
        };
        Update: {
          court_ids?: never;
          is_public?: boolean | null;
          line_id?: string | null;
          nickname?: string | null;
          ntrp?: number | null;
          open_to_greeting?: boolean | null;
          play_types?: never;
          share_presence?: boolean | null;
          slot_codes?: never;
        };
        Relationships: [];
      };
      my_session_participations: {
        Row: {
          can_cancel: boolean | null;
          can_confirm_attendance: boolean | null;
          can_confirm_played: boolean | null;
          can_respond_invite: boolean | null;
          can_withdraw: boolean | null;
          court: string | null;
          court_district: string | null;
          court_id: number | null;
          court_lat: number | null;
          court_lng: number | null;
          decided_at: string | null;
          fee_note: string | null;
          host_nickname: string | null;
          host_ntrp: number | null;
          host_profile_complete: boolean | null;
          id: number | null;
          join_mode: string | null;
          notes: string | null;
          ntrp_max: number | null;
          ntrp_min: number | null;
          play_type: string | null;
          range_end: string | null;
          session_id: number | null;
          slots_remaining: number | null;
          slots_total: number | null;
          sport_code: string | null;
          start_at: string | null;
          status: string | null;
          unread_message_count: number | null;
          updated_at: string | null;
          venue_type: string | null;
          viewer_participant_status: string | null;
          viewer_played_confirmed: boolean | null;
          viewer_role: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
        ];
      };
      player_directory: {
        Row: {
          court_district: string | null;
          court_id: number | null;
          court_lat: number | null;
          court_lng: number | null;
          court_name: string | null;
          is_self: boolean | null;
          nickname: string | null;
          ntrp: number | null;
          play_types: string[] | null;
          played_count: number | null;
          profile_id: number | null;
          slot_codes: string[] | null;
        };
        Relationships: [];
      };
      player_presence_directory: {
        Row: {
          court_district: string | null;
          court_id: number | null;
          court_lat: number | null;
          court_lng: number | null;
          court_name: string | null;
          is_self: boolean | null;
          minutes_ago: number | null;
          nickname: string | null;
          ntrp: number | null;
          open_to_greeting: boolean | null;
          profile_id: number | null;
        };
        Relationships: [];
      };
      session_contacts: {
        Row: {
          counterpart_profile_id: number | null;
          line_id: string | null;
          nickname: string | null;
          session_id: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["counterpart_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["counterpart_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["counterpart_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      session_discovery: {
        Row: {
          candidate_court_ids: number[] | null;
          court: string | null;
          court_district: string | null;
          court_id: number | null;
          court_lat: number | null;
          court_lng: number | null;
          decided_at: string | null;
          fee_note: string | null;
          host_nickname: string | null;
          host_ntrp: number | null;
          host_profile_complete: boolean | null;
          id: number | null;
          join_mode: string | null;
          notes: string | null;
          ntrp_max: number | null;
          ntrp_min: number | null;
          play_type: string | null;
          range_end: string | null;
          session_id: number | null;
          slots_remaining: number | null;
          slots_total: number | null;
          sport_code: string | null;
          start_at: string | null;
          status: string | null;
          venue_type: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "courts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["court_id"];
          },
          {
            foreignKeyName: "sessions_court_id_fkey";
            columns: ["court_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["court_id"];
          },
        ];
      };
      session_join_preview: {
        Row: {
          avatar_url: string | null;
          hosted_played_count: number | null;
          nickname: string | null;
          ntrp: number | null;
          role: string | null;
          session_id: number | null;
        };
        Relationships: [];
      };
      session_message_feed: {
        Row: {
          body: string | null;
          created_at: string | null;
          is_self: boolean | null;
          kind: string | null;
          message_id: number | null;
          sender_nickname: string | null;
          sender_profile_id: number | null;
          session_id: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "session_messages_sender_profile_id_fkey";
            columns: ["sender_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_messages_sender_profile_id_fkey";
            columns: ["sender_profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_messages_sender_profile_id_fkey";
            columns: ["sender_profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_messages_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      session_participant_roster: {
        Row: {
          home_courts: string[] | null;
          nickname: string | null;
          ntrp: number | null;
          participant_id: number | null;
          play_types: string[] | null;
          profile_id: number | null;
          role: string | null;
          session_id: number | null;
          status: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "player_presence_directory";
            referencedColumns: ["profile_id"];
          },
          {
            foreignKeyName: "session_participants_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "my_session_participations";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_discovery";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "session_join_preview";
            referencedColumns: ["session_id"];
          },
          {
            foreignKeyName: "session_participants_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      cancel_session: { Args: { p_session_id: number }; Returns: string };
      confirm_session_attendance: {
        Args: { p_session_id: number };
        Returns: string;
      };
      create_report: {
        Args: {
          p_message_id?: number;
          p_reason: string;
          p_reported_profile_id: number;
          p_session_id: number;
        };
        Returns: number;
      };
      create_session: {
        Args: {
          p_candidate_court_ids?: number[];
          p_court_id: number;
          p_fee_note?: string;
          p_join_mode?: string;
          p_notes: string;
          p_ntrp_max: number;
          p_ntrp_min: number;
          p_play_type: string;
          p_range_end?: string;
          p_slots_total: number;
          p_start_at: string;
          p_venue_type?: string;
        };
        Returns: number;
      };
      decide_session_court: {
        Args: { p_court_id: number; p_session_id: number; p_start_at: string };
        Returns: string;
      };
      invite_to_session: {
        Args: { p_profile_id: number; p_session_id: number };
        Returns: string;
      };
      mark_session_chat_read: {
        Args: { p_session_id: number };
        Returns: string;
      };
      mark_session_played: { Args: { p_session_id: number }; Returns: string };
      owns_notification_profile: {
        Args: { p_profile_id: number };
        Returns: boolean;
      };
      post_session_message: {
        Args: { p_body: string; p_session_id: number };
        Returns: string;
      };
      remove_push_subscription: {
        Args: { p_endpoint: string };
        Returns: string;
      };
      request_to_join_session: {
        Args: { p_session_id: number };
        Returns: string;
      };
      respond_to_session_invite: {
        Args: { p_decision: string; p_session_id: number };
        Returns: string;
      };
      review_join_request: {
        Args: {
          p_decision: string;
          p_participant_id: number;
          p_session_id: number;
        };
        Returns: string;
      };
      save_my_profile: {
        Args: {
          p_court_ids: number[];
          p_line_id: string;
          p_nickname: string;
          p_ntrp: number;
          p_play_types: string[];
          p_slot_codes: string[];
        };
        Returns: number;
      };
      save_push_subscription: {
        Args: { p_auth: string; p_endpoint: string; p_p256dh: string };
        Returns: string;
      };
      set_court_subscriptions: {
        Args: { p_court_ids: number[] };
        Returns: string;
      };
      set_notification_prefs: {
        Args: {
          p_chat_message_enabled: boolean;
          p_guest_invited_enabled: boolean;
          p_guest_request_reviewed_enabled: boolean;
          p_host_new_request_enabled: boolean;
          p_session_reminder_enabled: boolean;
          p_session_updated_enabled: boolean;
        };
        Returns: string;
      };
      set_open_to_greeting: { Args: { p_enabled: boolean }; Returns: string };
      set_player_block: {
        Args: { p_blocked: boolean; p_profile_id: number };
        Returns: string;
      };
      set_player_visibility: { Args: { p_visible: boolean }; Returns: string };
      set_presence_sharing: { Args: { p_enabled: boolean }; Returns: string };
      update_my_presence: {
        Args: { p_lat: number; p_lng: number };
        Returns: string;
      };
      update_session: {
        Args: {
          p_court_id: number;
          p_fee_note: string;
          p_note: string;
          p_ntrp_max: number;
          p_ntrp_min: number;
          p_play_type: string;
          p_session_id: number;
          p_slots_missing: number;
          p_start_at: string;
        };
        Returns: string;
      };
      withdraw_from_session: { Args: { p_session_id: number }; Returns: string };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const;
